### ISSUE TITLE
StoreTheIndex MVP Milestone

### ISSUE THREAD

**Issue by gammazero** [filecoin-project/storetheindex#32]
- [x] **Configuration**
  - [x] Configure home for all indexer data
  - [x] Define listen addresses addresses for all services
  - [x] Specify provider policy (block, allow, trust)
  - [x] Indexer core configuration
  - [x] Initialize node with default configuration file
   
- [x] **Discovery / registration**
  - [x] Direct registration from trusted provider
  - [x] Discover allowed miner on request
    - [x] Get peerID and multiaddr from lotus 
  - [x] List discovered providers
  - [x] HTTP
  - [x] Libp2
  - [x] Persist discovered providers
      - [x] Configure level DB datastore
      - [x] Save discovered providers
      - [x] Load saved providers on startup

- [x] **Ingestion**
  - [x] Immediate: registered provider can index limited CIDs + metadata
  - [x] Remove indexed CIDs
  - [x] Advertisement protocol
    - [x] Receive advert over gossip pub-sub
    - [x] Request previous adverts as needed
    - [x] Request advertised index data from provider
      - [x] Verify signature on advertisements
      - [x] Handle paginated responses

- [x] **FInder**
  - [x] Get data for single CID (provider ID, provider address, protocol + metadata)
  - [x] Get data for batch of CIDs
  - [x] HTTP
  - [x] Libp2p
   
 - [x] **Security**
   - [x] Messages for discovery and ingestion must be signed, verified using provider peer ID
   
- [x] **Deployment**
  - [x] Build docker image for storetheindex
    - [x] Define `Dockerfile`
    - [x] Allow persisted data on mapped volume
  - [x] Set cloud instance running indexer  
  - [x] Configure CI auto-deployment triggered on github merge
    
- [x] **Testing / Demo**
  - [x] Register fake providers
  - [x] Import fake index data for fake providers
  - [x] Demo client to query index data

**Comment by davidd8** [comment]
@gammazero updated the task list, please verify when you get a chance.

**Comment by davidd8** [comment]
@gammazero can we close out this issue?

**Comment by davidd8** [comment]
Marking all MVP tasks as complete.
